### ISSUE TITLE
Bug: UI constantly re-renders even when nothing changes

### ISSUE THREAD

**Issue by elimisteve** [cryptag/notes#13]
Notice that if I just view a document without changing anything, it eventually shows 200+ renders as of [this commit](https://github.com/cryptag/notes/commit/48f4245519a23fce0f5eab49b8696b34330bf429):

![screenshot-cryptag-notes-bug-constantlyrerendering-screenshot - 12142016 - 10 53 13 am](https://cloud.githubusercontent.com/assets/139603/21196174/908104b8-c1eb-11e6-9178-a2abc8bc791c.png)

**Comment by elimisteve** [comment]
@jimmcgaw I wouldn't care except Electron was using up to 13% CPU on my box.

Possible fix? https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate

...but hopefully we can just design the problem out of existence by avoiding doing some thing that React thinks should trigger a re-render; so far I don't see anything fishy, hmm...

**Comment by elimisteve** [comment]
More info: when it Edit mode, the re-rendering stops (as it should), which is good.

**Comment by elimisteve** [comment]
Possible fix #2 suggested at https://stackoverflow.com/questions/26556436/react-after-render-code , namely https://facebook.github.io/react/docs/react-component.html#componentdidupdate and https://facebook.github.io/react/docs/react-component.html#componentdidmount

**Comment by jimmcgaw** [comment]
Yep, shouldComponentUpdate is probably what we want to fix this issue. I didn't put any of that in b/c premature optimization = satan and all that. But if we're hitting a point where an interval is regularly updating the state and our CPUs are going nuts, then let's put something in.

At this point, still too early to do this by design for all components; let's just put this in where it's needed to keep our computers from catching fire.

**Comment by jimmcgaw** [comment]
I'm forgetting my commit message => github action mapping. "Fixes #xx" closes an issue, that's not what I intended. Please reopen if this commit doesn't solve the problem.

**Comment by elimisteve** [comment]
@jimmcgaw Perfect!!
